CUISINE_TOPICS = {
    'Pizza': '/m/0663v', 
    'Sushi': '/m/07030',
    'Kebab': '/m/022n8y',
    'Hamburger': '/m/0cdn1',
    'Taco': '/m/07crc',
    'Tacos français': '/g/11c6mbf6r2',
    'Restaurant gastronomique': '/g/121hfhdj',
    'restaurant chinois': '/m/0gx1rv4',
    'restaurant végétarien': '/g/11c5zrnmpz',
    'restaurant italien': '/g/11b6hhzwhm',
    'restaurant mexicain': '/g/11b6hffq31',
    'restaurant indien': '/g/11c2nk3hfl',
    'bar': '/m/01nz0z',
    'bistro': '/m/072qlz',
    'brasserie': '/m/025rvlt',
    'café': '/m/020fb2',
    'crêperie': '/g/1218fg9b',
    'pâtisserie': '/m/0hnyx',
    'traiteur': '/m/02yn76',
    'restaurant asiatique': '/g/11c5zt2ygg',
    'restaurant africain': '/g/11c5yss5mh',
    'restaurant américain': '/g/11c5xwqpht',
    'barbecue': '/g/1223qdcp',
}
